# Form implementation generated from reading ui file 'evenorodd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblInput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(90, 90, 91, 20))
        self.lblInput.setObjectName("lblInput")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(120, 270, 47, 14))
        self.lblResult.setObjectName("lblResult")
        self.btnCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheck.setGeometry(QtCore.QRect(210, 180, 75, 23))
        self.btnCheck.setObjectName("btnCheck")
        self.txtInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(180, 90, 141, 31))
        self.txtInput.setObjectName("txtInput")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(180, 260, 141, 31))
        self.txtResult.setObjectName("txtResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnCheck.clicked.connect(self.evenoroddcheck)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblInput.setText(_translate("MainWindow", "Enter a number:"))
        self.lblResult.setText(_translate("MainWindow", "Result:"))
        self.btnCheck.setText(_translate("MainWindow", "Check"))


    # 
    def evenoroddcheck(self):
        input_number = self.txtInput.text()

        #checks if input number is a digit
        if(input_number.isdigit()):
            input_number = int(input_number)
            
            #checks to see if input is even or odd
            if(input_number % 2 == 0):
                self.txtResult.setText("Number is Even")
            else:
                self.txtResult.setText("Number is Odd")
        else:
            #create a new MessageBox instance
            msg = QMessageBox()
            msg.setText("Please enter a valid number.")
            msg.setWindowTitle("Even or odd")
            msg.exec()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
