# Form implementation generated from reading ui file 'fruitCost.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbFruit.setGeometry(QtCore.QRect(170, 70, 141, 21))
        self.cbFruit.setObjectName("cbFruit")
        self.cbFruit.addItem("")
        self.cbFruit.addItem("")
        self.cbFruit.addItem("")
        self.cbFruit.addItem("")
        self.cbFruit.addItem("")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(140, 70, 21, 16))
        self.lblCost.setObjectName("lblCost")
        self.btnCheckout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCheckout.setGeometry(QtCore.QRect(200, 200, 75, 23))
        self.btnCheckout.setObjectName("btnCheckout")
        self.txtInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(180, 130, 113, 20))
        self.txtInput.setObjectName("txtInput")
        self.lblHowMany = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblHowMany.setGeometry(QtCore.QRect(110, 130, 61, 20))
        self.lblHowMany.setObjectName("lblHowMany")
        self.txtOutput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(180, 170, 113, 20))
        self.txtOutput.setObjectName("txtOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(120, 170, 61, 20))
        self.lblOutput.setObjectName("lblOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.cbFruit.activated.connect(self.dynamic_Cost)
        self.btnCheckout.clicked.connect(self.check_out)
    



    def dynamic_Cost(self):
            fruit_cost = 0

            if(self.cbFruit.currentText() == "Apple"):
                fruit_cost = 2
            elif(self.cbFruit.currentText() == "Banana"):
                fruit_cost = 1.5
            elif(self.cbFruit.currentText() == "Grapefruit"):
                fruit_cost = 4
            elif(self.cbFruit.currentText() == "Orange"):
                fruit_cost = 3
            elif(self.cbFruit.currentText() == "Peach"):
                fruit_cost = 2.5
        
            self.lblCost.setText(str(fruit_cost) + "$")

    def check_out(self):
    
            how_many = int(self.txtInput.text())
            if(self.cbFruit.currentText() == "Apple"):
                fruit_cost = 2
            elif(self.cbFruit.currentText() == "Banana"):
                fruit_cost = 1.5
            elif(self.cbFruit.currentText() == "Grapefruit"):
                fruit_cost = 4
            elif(self.cbFruit.currentText() == "Orange"):
                fruit_cost = 3
            elif(self.cbFruit.currentText() == "Peach"):
                fruit_cost = 2.5

            total = how_many * fruit_cost
            self.txtOutput.setText(str(total))
  

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCost.setText(_translate("MainWindow", "Fruit"))
        self.btnCheckout.setText(_translate("MainWindow", "Calculate"))
        self.lblHowMany.setText(_translate("MainWindow", "How many?"))
        self.lblOutput.setText(_translate("MainWindow", "Total Cost"))
        self.cbFruit.setItemText(0, _translate("MainWindow", "Apple"))
        self.cbFruit.setItemText(1, _translate("MainWindow", "Banana"))
        self.cbFruit.setItemText(2, _translate("MainWindow", "Grapefruit"))
        self.cbFruit.setItemText(3, _translate("MainWindow", "Orange"))
        self.cbFruit.setItemText(4, _translate("MainWindow", "Peach"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
