# Generated by Django 4.2 on 2025-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursetitle', models.CharField(max_length=100)),
                ('coursename', models.CharField(max_length=100)),
                ('studentsenrolled', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=100)),
                ('instructorname', models.CharField(max_length=100)),
            ],
        ),
    ]
