# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(330, 220, 141, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(340, 130, 113, 20))
        self.txtScore.setObjectName("txtScore")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(176, 130, 141, 20))
        self.lblScore.setObjectName("lblScore")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(344, 300, 113, 20))
        self.txtGrade.setText("")
        self.txtGrade.setObjectName("txtGrade")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(180, 300, 141, 20))
        self.lblGrade.setObjectName("lblGrade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # connects the calculate button to the grade calculator function
        self.btnCalculate.clicked.connect(self.grade_calculator)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate Grade"))
        self.lblScore.setText(_translate("MainWindow", "Enter Student Score"))
        self.lblGrade.setText(_translate("MainWindow", "Enter Student Score"))

    # calculates and returns a user letter grade based on input
    # takes input from score text box
    # throws error message box if number is greater than 100
    # throws error message box if input is not a number
    def grade_calculator(self):
        input_score = self.txtScore.text()
        grade = ""
        msg = QMessageBox()
        msg.setWindowTitle("Grade Calculator")
        

        if input_score.isdigit():
            input_score = int(input_score)
            # score must be between 100 and 0
            if(input_score < 101):
                # if number is between 100 and 90, it is an A and so forth
                if(input_score >= 90):
                    grade = "A"
                elif(input_score >= 80):
                    grade = "B"
                elif(input_score >= 70):
                    grade = "C"
                elif(input_score >= 60):
                    grade = "D"
                else:
                    grade = "F"
                self.txtGrade.setText(grade)
            else:
                # If the number is not between 0 and 100 throws an error
                msg.setText("Please enter a score between 0 and 100")
                msg.exec()
        else:
            # if the number is not a digit throw an error
            msg.setText("Please enter a valid score")
            msg.exec()                        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
