# Form implementation generated from reading ui file 'financialplanner.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAnnual = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAnnual.setGeometry(QtCore.QRect(220, 100, 131, 16))
        self.lblAnnual.setObjectName("lblAnnual")
        self.txtAnnual = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAnnual.setGeometry(QtCore.QRect(360, 100, 131, 20))
        self.txtAnnual.setObjectName("txtAnnual")
        self.lblTarget = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTarget.setGeometry(QtCore.QRect(220, 150, 131, 16))
        self.lblTarget.setObjectName("lblTarget")
        self.txtTarget = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTarget.setGeometry(QtCore.QRect(360, 150, 131, 20))
        self.txtTarget.setObjectName("txtTarget")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(220, 280, 131, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(360, 280, 131, 20))
        self.txtTime.setObjectName("txtTime")
        self.lblRetirement = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRetirement.setGeometry(QtCore.QRect(220, 190, 131, 16))
        self.lblRetirement.setObjectName("lblRetirement")
        self.cbRetirement = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbRetirement.setGeometry(QtCore.QRect(360, 190, 131, 22))
        self.cbRetirement.setObjectName("cbRetirement")
        self.cbRetirement.addItem("Plan 2040")
        self.cbRetirement.addItem("Plan 2050")
        self.cbRetirement.addItem("Plan 2060")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(360, 230, 131, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btnCalculate.clicked.connect(self.calculate_time_taken)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblAnnual.setText(_translate("MainWindow", "Enter Annual Amount"))
        self.lblTarget.setText(_translate("MainWindow", "Enter Target Amount"))
        self.lblTime.setText(_translate("MainWindow", "Time Taken"))
        self.lblRetirement.setText(_translate("MainWindow", "Select Retirement Plan"))
        self.btnCalculate.setText(_translate("MainWindow", "Calculate"))

    
    def calculate_time_taken(self):
        # Get user input value from Annual Amount text box
        annual_amount = int(self.txtAnnual.text())
        # Get user input value from Target Amount text box
        target_amount = int(self.txtTarget.text())
        # Get the users currently selected plan
        plan_selection = self.cbRetirement.currentText()

        years = 0
        # current portfolio value
        current_amount = 0

        if(plan_selection == "Plan 2040"):
            rate = 7.0
        elif(plan_selection == "Plan 2050"):
            rate = 6.0
        else:
            rate = 5.0
        
        while(current_amount < target_amount):
            current_amount = (current_amount + annual_amount) * (1+ rate/100)
            years = years + 1
        
        self.txtTime.setText(f"{years} years")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
