# Form implementation generated from reading ui file 'mortalkombat.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Player:
    def __init__(self, name, speed, power, agility):
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility

    def modify_stats(self, speed, power, agility):
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 741, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnCreate = QtWidgets.QPushButton(parent=self.tab)
        self.btnCreate.setGeometry(QtCore.QRect(290, 290, 141, 23))
        self.btnCreate.setObjectName("btnCreate")
        self.lblName = QtWidgets.QLabel(parent=self.tab)
        self.lblName.setGeometry(QtCore.QRect(200, 80, 121, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tab)
        self.txtName.setGeometry(QtCore.QRect(330, 80, 113, 20))
        self.txtName.setObjectName("txtName")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tab)
        self.txtSpeed.setGeometry(QtCore.QRect(330, 130, 113, 20))
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tab)
        self.lblSpeed.setGeometry(QtCore.QRect(200, 130, 121, 16))
        self.lblSpeed.setObjectName("lblSpeed")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tab)
        self.txtPower.setGeometry(QtCore.QRect(330, 180, 113, 20))
        self.txtPower.setObjectName("txtPower")
        self.lblPower = QtWidgets.QLabel(parent=self.tab)
        self.lblPower.setGeometry(QtCore.QRect(200, 180, 121, 16))
        self.lblPower.setObjectName("lblPower")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tab)
        self.txtAgility.setGeometry(QtCore.QRect(330, 230, 113, 20))
        self.txtAgility.setObjectName("txtAgility")
        self.lblAgility = QtWidgets.QLabel(parent=self.tab)
        self.lblAgility.setGeometry(QtCore.QRect(200, 230, 121, 16))
        self.lblAgility.setObjectName("lblAgility")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnModifyStats = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnModifyStats.setGeometry(QtCore.QRect(290, 400, 141, 23))
        self.btnModifyStats.setObjectName("btnModifyStats")
        self.txtModAgility = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModAgility.setGeometry(QtCore.QRect(540, 300, 113, 20))
        self.txtModAgility.setObjectName("txtModAgility")
        self.txtModName = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModName.setGeometry(QtCore.QRect(40, 300, 113, 20))
        self.txtModName.setObjectName("txtModName")
        self.lblModPower = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModPower.setGeometry(QtCore.QRect(370, 270, 121, 16))
        self.lblModPower.setObjectName("lblModPower")
        self.lblModName = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModName.setGeometry(QtCore.QRect(50, 270, 121, 16))
        self.lblModName.setObjectName("lblModName")
        self.lblModAgility = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModAgility.setGeometry(QtCore.QRect(540, 270, 121, 16))
        self.lblModAgility.setObjectName("lblModAgility")
        self.txtModSpeed = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModSpeed.setGeometry(QtCore.QRect(210, 300, 113, 20))
        self.txtModSpeed.setObjectName("txtModSpeed")
        self.lblModSpeed = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModSpeed.setGeometry(QtCore.QRect(210, 270, 121, 16))
        self.lblModSpeed.setObjectName("lblModSpeed")
        self.txtModPower = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModPower.setGeometry(QtCore.QRect(370, 300, 113, 20))
        self.txtModPower.setObjectName("txtModPower")
        self.lstPlayersCreated = QtWidgets.QListWidget(parent=self.tab_2)
        self.lstPlayersCreated.setGeometry(QtCore.QRect(220, 40, 256, 192))
        self.lstPlayersCreated.setObjectName("lstPlayersCreated")
        self.lblPlayersCreated = QtWidgets.QLabel(parent=self.tab_2)
        self.lblPlayersCreated.setGeometry(QtCore.QRect(300, 20, 121, 16))
        self.lblPlayersCreated.setObjectName("lblPlayersCreated")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Create an empty dictionary to store player objects when created
        self.created_players = {}
        # create player event
        self.btnCreate.clicked.connect(self.create_player)
        # modify player event
        self.btnModifyStats.clicked.connect(self.modify_stats)
        # display list item event
        self.lstPlayersCreated.itemClicked.connect(self.display_stats)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("mortalKombat", "Mortal Kombat"))
        self.btnCreate.setText(_translate("MainWindow", "Create Player"))
        self.btnModifyStats.setText(_translate("MainWindow", "Modify Stats"))
        self.lblName.setText(_translate("MainWindow", "Enter Player Name"))
        self.lblSpeed.setText(_translate("MainWindow", "Enter Player Speed"))
        self.lblPower.setText(_translate("MainWindow", "Enter Player Power"))
        self.lblAgility.setText(_translate("MainWindow", "Enter Player Agility"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Create Player"))
        self.lblModPower.setText(_translate("MainWindow", "Player Power"))
        self.lblModName.setText(_translate("MainWindow", "Player Name"))
        self.lblModAgility.setText(_translate("MainWindow", "Player Agility"))
        self.lblModSpeed.setText(_translate("MainWindow", "Player Speed"))
        self.lblPlayersCreated.setText(_translate("MainWindow", "Players Created"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Modify Stats"))

    def create_player(self):
        # To do: Add validations and exception handling blocks
        name = self.txtName.text()
        speed = self.txtSpeed.text()
        power = self.txtPower.text()
        agility = self.txtAgility.text()

        player_object = Player(name, speed, power, agility)

        # The dictionary will have player name as the key and player object as the value
        self.created_players[name] = player_object
        
        self.lstPlayersCreated.addItem(name)

        # Display a message box: Player Created


    def display_stats(self, item):
        # Get the name of the currently selected player in the list widget
        selected_player = item.text()
        player_object = self.created_players.get(selected_player)

        self.txtModName.setText(player_object.player_name)
        self.txtModSpeed.setText(player_object.player_speed)
        self.txtModPower.setText(player_object.player_power)
        self.txtModAgility.setText(player_object.player_agility)

    def modify_stats(self):
        
        name = self.txtName.text()
        speed = self.txtModSpeed.text()
        power = self.txtModPower.text()
        agility = self.txtModAgility.text()

        player_object = self.created_players.get(name)
        self.created_players[name] = player_object


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
